openapi: 3.2.0
info:
  title: Proxmox Orchestration API
  description: A RESTful API that provides access to Proxmox environment information and enables administrators to manage the lifecycle of game servers running inside Proxmox LXC containers.
  contact:
    name: Bruno Biz Dias de Castro
    url: https://github.com/BrunoBiz
    email: brunobizdc@gmail.com
  version: 1.0.0
tags:
  - name: Containers
    description: Operations for retrieving and managing Proxmox LXC containers.
  - name: Services
    description: Operations for managing game server services running within Proxmox LXC containers.
servers:
  - url: http://192.168.18.162:8090
    name: "Local Proxmox container IP"
paths:
  /containers:
    get:
      tags:
          - Containers
      summary: List all containers
      description: Will consult via the Proxmox PVE and return all available LXC containers, be them enabled or disabled
      operationId: listContainers
      responses:
        '200':
          description: An array of containers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Containers'
        default:
          description: Unexpected error
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      description: Any error returned as internal server error - 500
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string    
    Containers:
      type: array
      description: List of containers
      items:
        $ref: '#/components/schemas/Container'      
    Container:
      type: object
      description: Each container represents a Proxmox LXC
      required:
        - ContainerConfig
        - CPUs
        - MaxDisk
        - MaxMem
        - MaxSwap
        - Name
        - Node
        - Status
        - Tags
        - Uptime
        - VMID
      properties:
        Client:
          type: object
        ContainerConfig:
          type: object
        CPUs:
          type: int
        MaxDisk:
          type: int
          format: uint64
        MaxMem:
          type: int
          format: uint64 
        MaxSwap:
          type: int
          format: uint64
        Name:
          type: string
        Node:
          type: string
        Status:
          type: string
        Tags:
          type: string
        Uptime:
          type: int
          format: uint64
        VMID:
          type: StringOrUint64